name:                lab-applicatives
version:             0.2.0.0
github:              "fpclass/lab-applicatives"
license:             MIT
author:              "Michael B. Gale"
maintainer:          "m.gale@warwick.ac.uk"
copyright:           "Copyright 2020 Michael B. Gale"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/fpclass/lab-applicatives#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  lab7-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    dependencies:
    - lab-applicatives
    - hspec
    - QuickCheck
